### PR TITLE
new blog post introducing ukvm

### PR DESCRIPTION
**Pull request by perbu**
Hi.

I wrote an introduction to ukvm/solo5 some time ago which I think is relevant here.

### CODE REVIEW

**Comment by mato** [comment]
TBH, I think it's too early for this post, for two reasons:

1. We don't yet have a formal release of Solo5 with support for IncludeOS.
2. The Solo5 and ukvm architecture is still too much in flux for calling out to PaaS/cloud providers to support it.

/cc @djwillia @ricarkol

**Comment by ricarkol** [comment]
Just wanted to mention something about point 1 above. IncludeOS master is pointing to my personal repo until https://github.com/hioa-cs/IncludeOS/issues/1435 gets fixed. #1435 is really the only change needed for IncludeOS to run on top of solo5. The other change would be "liveupdate" support which is also implemented in my repo but could wait.

Regarding point 2. Mato is in the middle of defining a better Solo5 public interface. @perbu , you can follow the status of that effort here: https://github.com/Solo5/solo5/pull/201.

**Comment by perbu** [comment]
Hi, @mato, I'm fine waiting until we the issue referenced by @ricarkol is resolved before publishing. This makes sense for us. We've published an includeos-specific post on our own and the pan-unikernel aspects can wait.

Regarding  pt2 - I don't think we'll need for Solo5 to be _perfect_ before calling attention to it. The major PaaS providers will move slowly and consider the steps thoroughly along the way and likely there will be quite a bit of work needed to do that kind of deployment. We'll likely notice if it should ever happen.

In general I think Solo5 is a bit under-communicated. Except for a published paper and a presentation there really isn't much content outlining the potential impact Solo5 could have on modern IT architecture.

I'll ping the PR once hioa-cs/IncludeOS#1435 is resolved and we can pick it up then.

Cheers,

**Comment by djwillia** [comment]
I like the post!  The more we get the ideas out the better!

To mato's second point, maybe the wording makes it sound like it's a bit too easy for the cloud providers.  In reality, it seems there will be a lot of things to be figured out around how to orchestrate these unikernels... a cloud provider can't just add a backend to openstack or whatever and expect to get many of the benefits (because it was designed for big, slow VMs).  Probably a lot of rethinking of how to build orchestration will be needed to really get the benefits we all want to see.  Perhaps a mention of some of these upcoming challenges is worth adding, to reduce mato's concern?

**Comment by amirmc** [comment]
@djwillia @ricarkol, if @perbu doesn't mind, I think it'd be great to have you as co-authors to this piece.  If there are sections you think you could add, that'd be great.

Let me know what you all think.

**Comment by perbu** [comment]
(Sorry for the late reply. This drowned in the constant flood of emails from Github).

I don't mind at all. Quite the opposite. One of the reasons I like Solo5 is because it has the potential to bring several unikernels (and potentially other operating systems) together. So if @djwillia and @ricarkol want to alter the post so they are comfortable putting their name on it - go right ahead.

**Comment by perbu** [comment]
hioa-cs/IncludeOS#1435 is now closed and IncludeOS now builds with the master branch of Solo5 from the official repo. 

@mato, any concrete plans to roll a release?

**Comment by mato** [comment]
@perbu Can we please move Solo5 release-related discussion to https://github.com/Solo5/solo5/issues/217? You can see the list of tasks that need doing before a release there.

**Comment by perbu** [comment]
Hey @mato 

Solo5/solo5#217 is closed? Shall we merge this in?

**Comment by mato** [comment]
@perbu Personally I'd prefer if you (the IncludeOS team) write up a blog / article / howto specifically about building IncludeOS unikernels with Solo5.

This (now somewhat out of date) article is more of a general article about Solo5/ukvm. I don't think it's terribly useful in it's current form, especially given the general goals of Solo5 as [documented](https://github.com/Solo5/solo5/blob/master/docs/architecture.md) and imminent [rename](https://github.com/Solo5/solo5/issues/172) of `ukvm` post the 0.3.0 release. 

Also, I've no idea if unikernel.org has any readership these days, do you folks have a blog of your own?

**Comment by perbu** [comment]
Thanks.

I'll delete the PR.

**Pull request closed without merging**
